repos:
-   repo: https://github.com/checkmake/checkmake.git
    # Or another commit hash or version
    rev: 0.2.2
    hooks:
    # Use this hook to let pre-commit build checkmake in its sandbox
#    -   id: checkmake
    # OR Use this hook to use a pre-installed checkmake executable
     -   id: checkmake-system