# SPDX-FileCopyrightText: Copyright (c) 2025 Roman Lupashko (CuberHuber)
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".pdd",
    "**.json",
    "**.md",
    "**.txt",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "README.md",
    "renovate.json"
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Roman Lupashko (CuberHuber)"
SPDX-License-Identifier = "MIT"
