name: lint-make

on:
  pull_request:
    branches:
      - master
      - main
      - lint
    paths:
      - 'Makefile'
      - 'makefile'
      - 'GNUmakefile'
      - '**.mk'
      - '**.make'
  push:
    paths:
      - 'Makefile'
      - 'makefile'
      - 'GNUmakefile'
      - '**.mk'
      - '**.make'

jobs:
  checkmake:
    name: Check Makefile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install checkmake
        run: |
          # Install the checked version used in .pre-commit-config.yaml
          go install github.com/checkmake/checkmake@v0.2.2
          # Ensure GOPATH/bin is on PATH for subsequent steps
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run checkmake
        run: |
          checkmake

